
DROP TABLE IF EXISTS user_social;


CREATE TABLE user_social (
    `ID` CHAR(36) PRIMARY KEY,
    `USER_ID` CHAR(36) NOT NULL,
    `PROVIDER` VARCHAR(50) NOT NULL,
    `SOCIAL_ID` VARCHAR(255) NOT NULL,
    `CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES user(id)
);
